"""add phone column to users

Revision ID: 79694d354f09
Revises: f2a8d0fb9329
Create Date: 2026-03-11 21:04:11.209791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79694d354f09'
down_revision: Union[str, Sequence[str], None] = 'f2a8d0fb9329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'phone', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
